services:
  kitchen1:
    build:
      context: .
      dockerfile: Dockerfile  
      args:
          configurations: configurations
          port: 8080
    ports:
      - "8080:8080" 

  kitchen2:
    build:
      context: .
      dockerfile: Dockerfile  
      args:
          configurations: configurations2
          port: 8081
    ports:
      - "8081:8081"
networks:
  default:
    name: restaurant
    external: true 